courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.course_list),
	url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail),
	url(r'(?P<pk>\d+)/$', views.course_detail),
]

learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
	url(r'^courses/', include('courses.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.hello_world)
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=255)
	description = models.TextField()

	def __str__(self):
		return self.title


class Step(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	content = models.TextField(blank=True, default='')
	order= models.IntegerField(default=0)
	course = models.ForeignKey('Course')

	class Meta:
		ordering = ['order',]

	def __str__(self):
		return self.title

courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Course, Step
# Create your views here.
def course_list(request):
	courses = Course.objects.all()
	return render(request, 'courses/course_list.html', {'courses':courses})


def course_detail(request, pk):
	course = get_object_or_404(Course, pk=pk)
	return render(request, 'courses/course_detail.html', {'course':course}) 


def step_detail(request, course_pk, step_pk):
	step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
	return render(request, 'courses/step_detail.html', {'step':step})

learning_site/views.py
from django.shortcuts import render


def hello_world(request):
	return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content%}
<article>
<h2>{{ course.title }}</h2>
{{ course.description }}

	<section>
		{% for step in course.step_set.all %}
		<h3>{{ step.title }}</h3>
			{{ step.description }}
		{% endfor %}
	</section>
</article>
{% endblock %}

courses/templates/courses/course_list.html
<div>
	{% for course in courses %}
	<h2>{{ course.title }}</h2>
	{{ course.description }}
	{% endfor%}
</div>

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
	<article>
		<h2>{{ step.course.title }}</h2>
		<h3>{{ step.title }}</h3>
		{{ step.content|linebreaks }}
	</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title%}Well hello there{% endblock%}

{% block content %}
<h1>Welcome! </h1>

{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/layout.css' %}">
</head>
<body>

	<div class="site-container">
		<nav>
			<a href="{% url 'views.hello_world' %}">Home</a>
			<a href="{% url 'courses.views.course_list' %}">Courses</a>
		</nav> 
	<h1>Welcome</h1>
	<h4>Please enter your name and Email:</h4>
	<form action="post">
		<label for="name">First and Last Name:</label>
	<input type="text" name="name">
	<br>
	<br>
		<label for="email">Email address</label>
	<input type="text" name="email">
	</form>
</html>